// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByB7dt5n1W6W-3bZIXkndlt_w_34MrvQc',
    appId: '1:236600949564:web:425641aa2ad6bcb582fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    authDomain: 'neuse-news-df5fd.firebaseapp.com',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHkIGUB7Et0OoTgChoORHdjz01QYGM5k',
    appId: '1:236600949564:android:1290ec24f72f09c482fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLGdDTvwCFYmMF486cEGfiRgDqLZyP62Y',
    appId: '1:236600949564:ios:7b5dd756c5ca794b82fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLGdDTvwCFYmMF486cEGfiRgDqLZyP62Y',
    appId: '1:236600949564:ios:7b5dd756c5ca794b82fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByB7dt5n1W6W-3bZIXkndlt_w_34MrvQc',
    appId: '1:236600949564:web:957a3d2cf2d8ac4d82fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    authDomain: 'neuse-news-df5fd.firebaseapp.com',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
  );
}
